### ISSUE TITLE
SortAlgorithmsComparer anpassen

### ISSUE THREAD

**Issue by iAmWhyy** [iAmWhyy/Testat_1_FSY#2]
SortAlgorithmsComparer anpassen, sodass bestimmte Arrays (int[]) mit allen Algorithmen sortiert werden und die Zeiten gespeichert werden.

Außerdem die Ausgabe anpassen:
[Arraybeschreibung]
[Array (falls nicht zu lang)]
[Sortieralgorithmus 1]: [Zeit, die der Algorithmus gebraucht hat]
[Sortieralgorithmus 2]: [Zeit, die der Algorithmus gebraucht hat]
[Sortieralgorithmus 3]: [Zeit, die der Algorithmus gebraucht hat]

**Comment by wiegardfl** [comment]
Das würde ich übernehmen.

**Comment by iAmWhyy** [comment]
Sehr gut, werde nachher einen PR machen, in dem der ArrayCreator angepasst ist. Wenn einer drüber geschaut hat und der PR fertig ist, kannst du ja den Master nochmal mit deinem Branch mergen, damit du dir auch die Arrays, die wir zum Testen verwenden werden erzeugen kannst.

**Comment by iAmWhyy** [comment]
Achso und schaue vielleicht auch schon mal in issue#4, da es dort um die Speicherung der Daten geht und das gewissermaßen mit diesem Problem verknüpft ist. Also denke ich mal

**Comment by wiegardfl** [comment]
> 
> 
> Achso und schaue vielleicht auch schon mal in issue#4, da es dort um die Speicherung der Daten geht und das gewissermaßen mit diesem Problem verknüpft ist. Also denke ich mal

Jo, das stimmt. Ich schau mal
