### ISSUE TITLE
SortAlgorithmAndRuntime anpassen

### ISSUE THREAD

**Issue by iAmWhyy** [iAmWhyy/Testat_1_FSY#4]
Idee: Nicht für jeden Algorithmus ein eigenes Objekt, welches die Zeiten speichert, sondern für jedes bestimmte Array ein Objekt, welches folgende Properties aufweist:
- Benennung des Arrays (bzw. spezielle Eigenschaften)
- das Array selbst
- Name Algorithmus1 und Laufzeit
- Name Algorithmus2 und Laufzeit
- Name Algorithmus3 und Laufzeit
....

**Comment by wiegardfl** [comment]
Behalten wir die mehreren Ausführungen (numberOfRuns) pro Array-Variation in SortAlgorithmsComparer mit Min, Max, und Average bei? Wenn ja, dann müssten wir festlegen, ob wir die Zeiten der einzelnen Runs schon für jede Array-Variation zusammenfassen oder ob wir für jeden Run einen eigenen Eintrag generieren.

**Comment by iAmWhyy** [comment]
Nein, würde keine NumberOfRuns machen,. sondern immer ein bestimmtes Array (mit bestimmten Eigenschaften nehmen) und dann jeden Sortieralgorithmus drauf anwenden und die Zeiten speichern. Deshalb auch das Objekt nicht für jeden Algorithmus erstellen, sondern für jedes Array.m Wenn du willst, können wir auch DC gehen

**Comment by iAmWhyy** [comment]
So ist alles im Master drinnen, kannst ihn nun mergen, sobald du die Arrays benötigst

**Comment by wiegardfl** [comment]
> 
> 
> Nein, würde keine NumberOfRuns machen,. sondern immer ein bestimmtes Array (mit bestimmten Eigenschaften nehmen) und dann jeden Sortieralgorithmus drauf anwenden und die Zeiten speichern. Deshalb auch das Objekt nicht für jeden Algorithmus erstellen, sondern für jedes Array.m Wenn du willst, können wir auch DC gehen

Alles klar. Macht es etwas einfacher.
Ich pushe die Changes, die ich bis jetzt habe erstmal in den Branch ohne PR. Merge und den Rest mache ich dann morgen.

**Comment by iAmWhyy** [comment]
Alles klar, wäre cool, wenn du die Issues am besten mit dem PR verknüpfst.
