### ISSUE TITLE
Bugfix CountingSort

### ISSUE THREAD

**Issue by wiegardfl** [iAmWhyy/Testat_1_FSY#7]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -21474 out of bounds for length 100001
	at CountingSort.sort(Program.java:450)

**Comment by iAmWhyy** [comment]
Jo, schaue jetzt mal drüber

**Comment by iAmWhyy** [comment]
Branch: bugfix_countingSortException

**Comment by iAmWhyy** [comment]
Kann mir aktuell den Fehler noch nicht wirklich erklären, habe mal einen etwas anderen CountingSort Algo verwendet, selber Fehler wie zuvor, das ist aber nur bei dem Array der Länge 100.000, wenn ich das auf 99.999 stelle, funktioniert alles tadellos. Lustigerweise, wenn ich die Länge auf 1.000.000 stelle, dann fliegen die Exceptions im Randomized Quicksort. 
Aber es scheint so, als hätte der Counting Sort Probleme mit Arrays, die eine 6 stellige Länge haben (auch 110.000 wirft eine Exception mit etwas anderem negativem Index)

**Comment by iAmWhyy** [comment]
Er bricht in dem Comparer immer bei folgendem Fall ab, aber wenn man ihn wie hier extrahiert durch den CountingSort jagd, dann geht es einwandfrei:

```
int maxNumber = 100000;
var arrForSorting = ArrayInputCreator.createArrayWithRndVals(100000, maxNumber);
var ct = new CountingSort();
ct.sort(arrForSorting, maxNumber);
```
